/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.gui;

import client.controller.ActivitateController;
import client.controller.AngajatController;
import static client.gui.AdminFrame.logger;
import db.Activitate;
import db.Angajat;
import java.awt.Color;
import java.io.File;
import java.io.PrintWriter;
import java.rmi.RemoteException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Razvan
 */
public class AngajatiLenesiFrame extends javax.swing.JFrame {

    /**
     * Creates new form AngajatiLenesiFrame
     */
    public DefaultListModel model;
    public AngajatiLenesiFrame() {
        initComponents();
        
        setTitle("Angajatii care nu au bagat pontaje!");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
        
        model = new DefaultListModel();
        model.removeAllElements();
        jList1.setModel(model);
        
        getContentPane().setBackground(Color.WHITE);
        
        jDateChooser1.setDate(new Date());
        jDateChooser2.setDate(new Date());
        
        afisare();
    }
    
    public void afisare(){
        LocalDate startDate = jDateChooser1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate endDate = jDateChooser2.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        if(startDate.isAfter(endDate)){
            JOptionPane.showMessageDialog(null, "Incearca sa pui invers datele");
            return;
        }
        try {
            model.removeAllElements();
            
            List<Angajat> angajati = AngajatController.getInstance().getAngajatiByStare("activ");
            for(Angajat a:angajati){
                List<Activitate> pontaje = ActivitateController.getInstance().getActivitatiPerioada(a,Date.from(startDate.atStartOfDay(ZoneId.systemDefault()).toInstant())
                        ,Date.from(endDate.atStartOfDay(ZoneId.systemDefault()).toInstant()));
                for (LocalDate date = startDate; date.isBefore(endDate.plusDays(1)); date = date.plusDays(1)){
                    pontaje = ActivitateController.getInstance().getActivitatiPerioada(a,Date.from(date.atStartOfDay(ZoneId.systemDefault()).toInstant())
                        ,Date.from(date.atStartOfDay(ZoneId.systemDefault()).toInstant()));
                    if(pontaje.isEmpty() && !a.getNume().equals("Melinceanu Cristiana")){
                        String add = a.getNume()+ " " + date + " ";
                        switch(date.getDayOfWeek().toString()){
                            case "MONDAY":{
                                add+="Luni";
                                model.addElement(add);
                            }break;
                            case "TUESDAY":{
                                add+="Marti";
                                model.addElement(add);
                            }break;
                            case "WEDNESDAY":{
                                add+="Miercuri";
                                model.addElement(add);
                            }break;
                            case "THURSDAY":{
                                add+="Joi";
                                model.addElement(add);
                            }break;
                            case "FRIDAY":{
                                add+="Vineri";
                                model.addElement(add);
                            }break;
                            
                        }
                    }
                }

            }
        } catch (RemoteException ex) {
            logger.error("Eroare la admin!");
            ex.printStackTrace();
        }catch (Exception e){
            logger.error("Eroare micuta!");
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("De la:");

        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Pana la:");

        jDateChooser2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Afisare");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(jList1);

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Export");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        afisare();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.showSaveDialog(this);
            File file = fileChooser.getSelectedFile();
            int index = file.getName().lastIndexOf('.');
            String name;
            if (index>-1) {
                name = file.getName().substring(0,index);
            }else name = file.getName();
            file = new File(file.getParent() + "/" + name + ".txt");
            PrintWriter writer = new PrintWriter(file);
            for(int i=0;i<model.getSize();i++){
                writer.println(model.getElementAt(i));
            }
            writer.close();
        }catch(Exception e){
            logger.error(e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
