/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.gui;

import client.controller.ActivitateController;
import client.controller.ProiectController;
import db.Activitate;
import db.Angajat;
import db.Proiect;
import java.rmi.RemoteException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author razvan
 */
public class ClientFrame extends javax.swing.JFrame {

    public Angajat angajat;
    private int cod;
    private Proiect proiect;
    
    public ClientFrame(Angajat angajat) {
        initComponents();
        
        this.angajat = angajat;
        
        setLocationRelativeTo(null);
        setVisible(true);
        setTitle(angajat.getNume());
        
        populareComboProiect();
        populareComboEtapa();
        
        jLabel4.setVisible(false);
        jComboBox4.setVisible(false);
        
        jLabel5.setVisible(false);
        jTextField1.setVisible(false);
        
        jTextArea1.setEditable(false);
    }
    
    public void populareComboProiect(){
        try {
            List<Proiect> lista = ProiectController.getInstance().getAll();
            for(Proiect p : lista){
                jComboBox1.addItem(p.getNume());
            }
        } catch (RemoteException ex) {
            Logger.getLogger(ClientFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void populareComboEtapa(){
        jComboBox2.addItem("Discutii");
        jComboBox2.addItem("Proiectare");
        jComboBox2.addItem("Santier");
        jComboBox2.addItem("Reproiectare");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Proiect:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Adauga");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Etapa:");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Stadiu:");

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nivel:");

        jComboBox4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Etaj:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setMinimumSize(new java.awt.Dimension(39, 28));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Ore:");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setMinimumSize(new java.awt.Dimension(39, 28));
        jTextField2.setName(""); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Minute:");

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(364, 364, 364))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{                                         
            Activitate pontaj = new Activitate();
            pontaj.setAngajat(angajat);
            pontaj.setDataOra(new Date());
            if (jTextField1.isVisible()){
                int etaj = Integer.parseInt(jTextField1.getText());
                if((etaj>=0 && etaj<=proiect.getNrEtaje()) || (etaj<0 && etaj>=proiect.getNrEtajeSubsol()))
                    pontaj.setEtaj(Integer.parseInt(jTextField1.getText()));
            }
            int ore = Integer.parseInt(jTextField2.getText());
            if (ore > 0)
                pontaj.setOreMunca(ore);
            else {
                JOptionPane.showMessageDialog(null, "Numar de ore incorect!");
                return;
            }
            int minute = Integer.parseInt(jTextField3.getText());
            if (minute >= 0 && minute < 60)
                pontaj.setMinuteMunca(minute);
            else {
                JOptionPane.showMessageDialog(null, "Numar de minute incorect!");
                return;
            }
            cod = cod*100 + jComboBox3.getSelectedIndex() + 1;
            if (jComboBox4.isVisible()) cod = cod*100 + jComboBox4.getSelectedIndex();
            else cod*=100;
            //JOptionPane.showMessageDialog(null, cod + " " + pontaj.getDataOra().toString());
            pontaj.setCod(cod);
            pontaj.setProiect(proiect);
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Pontajul dumneavoastra: "+pontaj.toString()+" " 
                    +"\nDoriti sa continuati?","Confirmare!",dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION)
                ActivitateController.getInstance().adaugaActivitate(pontaj);
            cod = jComboBox2.getSelectedIndex()+11;
        }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Nu ati introdus un numar!");
        } catch (RemoteException ex) {
            Logger.getLogger(ClientFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String etapa = jComboBox2.getSelectedItem().toString();
        jComboBox3.removeAllItems();
        jComboBox4.removeAllItems();
        switch(etapa){
            case "Discutii":{
                cod = 11;
                jComboBox3.addItem("Beneficiar");
                jComboBox3.addItem("Colaborator");
                jLabel4.setVisible(false);
                jComboBox4.setVisible(false);
                
                jLabel5.setVisible(false);
                jTextField1.setVisible(false);
            }break;
            case "Proiectare":{
                cod = 12;
                jComboBox3.addItem("Calcul");
                jComboBox3.addItem("Detaliere");
                jComboBox3.addItem("Coordonare");
                jComboBox3.addItem("Verificare");
                jComboBox3.addItem("Editie");
            }break;
            case "Santier":{
                cod = 13;
                jComboBox3.addItem("Grinzi");
                jComboBox3.addItem("Stalpi");
                jComboBox3.addItem("Pereti");
                jComboBox3.addItem("Placi");
                jComboBox3.addItem("Altele");
                jLabel4.setVisible(false);
                jComboBox4.setVisible(false);
                
                jLabel5.setVisible(true);
                jTextField1.setVisible(true);
                //jTextField1.setSize(390, 200);
            }break;
            case "Reproiectare":{
                cod = 14;
                jComboBox3.addItem("Calcul");
                jComboBox3.addItem("Detaliere");
                jLabel4.setVisible(true);
                jComboBox4.setVisible(true);
            }break;
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        int index = jComboBox3.getSelectedIndex()+1;
        jComboBox4.removeAllItems();
        switch(cod){
            case 11:{
                //cod = (cod*100 + index)*10000; 
            }break;
            case 12:{
                //cod = cod*100 + index;
                
                switch(index){
                    case 1:{
                        jLabel4.setVisible(true);
                        jComboBox4.setVisible(true);
                        jComboBox4.addItem("Global");
                        jComboBox4.addItem("Grinzi");
                        jComboBox4.addItem("Stalpi");
                        jComboBox4.addItem("Pereti");
                        jComboBox4.addItem("Placi");
                        jComboBox4.addItem("Altele");
                    }break;
                    case 2:{
                        jLabel4.setVisible(true);
                        jComboBox4.setVisible(true);
                        jComboBox4.setEnabled(true);
                        jComboBox4.addItem("Grinzi");
                        jComboBox4.addItem("Stalpi");
                        jComboBox4.addItem("Pereti");
                        jComboBox4.addItem("Placi");
                        jComboBox4.addItem("Altele");
                    }break;
                    case 3:{
                        jLabel4.setVisible(true);
                        jComboBox4.setVisible(true);
                        jComboBox4.setEnabled(true);
                        jComboBox4.addItem("Global");
                        jComboBox4.addItem("Grinzi");
                        jComboBox4.addItem("Stalpi");
                        jComboBox4.addItem("Pereti");
                        jComboBox4.addItem("Placi");
                        jComboBox4.addItem("Altele");
                    }break;
                    case 4:{
                        jLabel4.setVisible(true);
                        jComboBox4.setVisible(true);
                        jComboBox4.setEnabled(true);
                        jComboBox4.addItem("Global");
                        jComboBox4.addItem("Grinzi");
                        jComboBox4.addItem("Stalpi");
                        jComboBox4.addItem("Pereti");
                        jComboBox4.addItem("Placi");
                        jComboBox4.addItem("Altele");
                    }break;
                    case 5:{
                        jLabel4.setVisible(false);
                        jComboBox4.setVisible(false);
                    }break;
                }
            }break;
            case 13:{
                
            }break;
            case 14:{
                switch(index){
                    case 1:{
                        jComboBox4.setEnabled(true);
                        jComboBox4.addItem("Global");
                        jComboBox4.addItem("Grinzi");
                        jComboBox4.addItem("Stalpi");
                        jComboBox4.addItem("Pereti");
                        jComboBox4.addItem("Placi");
                        jComboBox4.addItem("Altele");
                    }break;
                    case 2:{
                        jComboBox4.setEnabled(true);
                        jComboBox4.addItem("Grinzi");
                        jComboBox4.addItem("Stalpi");
                        jComboBox4.addItem("Pereti");
                        jComboBox4.addItem("Placi");
                        jComboBox4.addItem("Altele");
                    }break;
                }
            }
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        int index1 = jComboBox3.getSelectedIndex();
        int index2 = jComboBox4.getSelectedIndex();
        
        if((cod == 12 || cod == 14) && (index1 == 0 || index1 == 2 || index1 == 3) && index2 == 0){
            jLabel5.setVisible(false);
            jTextField1.setVisible(false); 
            jTextField1.removeAll();
        }else{
            jLabel5.setVisible(true);
            jTextField1.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        try {
            jTextArea1.setText(null);
            proiect = ProiectController.getInstance().findByNume((String)jComboBox1.getSelectedItem());
            jTextArea1.append("Nume proiect: "+proiect.getNume()+"\n");
            jTextArea1.append("Nume beneficiar: "+proiect.getBeneficiar()+"\n");
            jTextArea1.append("Adresa: "+proiect.getAdresa()+"\n");
            jTextArea1.append("Numar de etaje: "+proiect.getNrEtaje()+"\n");
            jTextArea1.append("Numar de etaje subsol: "+proiect.getNrEtajeSubsol()+"\n");
            jTextArea1.append("Nume arhitect: "+proiect.getNumeArhitect()+"\n");
        } catch (RemoteException ex) {
            Logger.getLogger(ClientFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
