    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.gui;

import client.controller.ProiectController;
import db.Proiect;
import java.awt.BorderLayout;
import java.awt.Font;
import java.nio.file.Paths;
import java.rmi.RemoteException;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import org.apache.log4j.PropertyConfigurator;

/**
 *
 * @author Razvan
 */
public class EtajeFrame extends javax.swing.JFrame {

    /**
     * Creates new form EtajeFrame
     */
    private int etaje;
    private int subsol;
    private JTable tabel;
    private Proiect proiect;
    private int nr;
    boolean mod;
    private final String pathToLog4j = Paths.get("./log4j.properties").toString();
    public static final org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger(EtajeFrame.class);
    
    public EtajeFrame(Proiect proiect,int etaje,int subsol,int nr,boolean mod) {
        initComponents();
        PropertyConfigurator.configure(Paths.get(pathToLog4j).toString());
        String []header = {"Etaj","Suprafata"};
        this.nr = nr;
        this.mod = mod;
        
        setTitle("Corp "+nr);
        JOptionPane.showMessageDialog(null, "Suprafata etajelor pentru corpul cu numarul "+nr);
        
        this.etaje = etaje;
        this.subsol = subsol;
        this.proiect = proiect;
        
        Object [][] data = new Object[etaje+subsol+1][2];
        
        for(int i=-subsol;i<=etaje;i++){
            data[i+subsol][0] = "Etaj "+ i;
            data[i+subsol][1] = "0";
        }
        
        tabel = new JTable(data,header){
            public boolean isCellEditable(int row,int coll){
                if(coll==1) return true;
                return false;
            }
        };
        JScrollPane scrollpane = new JScrollPane(tabel);
        
        tabel.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 18));
        tabel.setFont(new Font("Tahoma", Font.PLAIN, 18));
        
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(scrollpane);
        
        
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Adauga");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(216, 216, 216))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String etaj="";
            int suma=0;
            for(int i=0;i<=subsol+etaje;i++){
                if (tabel.getValueAt(i, 1)==null){
                    JOptionPane.showMessageDialog(null, "Un camp este gol!");
                    return;
                }
                if (Integer.parseInt((String)tabel.getValueAt(i, 1))<0){
                    JOptionPane.showMessageDialog(null, "Un numar nu este corect!");
                    return;
                }
                etaj=etaj+tabel.getValueAt(i, 1)+" ";
                suma+= Integer.parseInt((String)tabel.getValueAt(i, 1));
            }
            JOptionPane.showMessageDialog(null, "Suprafata desfasurata este: "+suma);
            if (nr==1) proiect.setSuprafataEtaj(etaj);
            else proiect.setSuprafataEtaj(proiect.getSuprafataEtaj()+'\n'+etaj);
            proiect.setStare(0);
            
            if(nr<proiect.getCorpuri()){
                dispose();
                new EtajeFrame(proiect, proiect.getNrEtaje(),proiect.getNrEtajeSubsol(),nr+1,mod).setVisible(true);
            }else{
                if(nr==proiect.getCorpuri()){
                    dispose();
                    if(mod) ProiectController.getInstance().modifyProject(proiect);
                    else ProiectController.getInstance().adaugaProiect(proiect);
                    AdminFrame.afisare();
                }
            }
            dispose();
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Nu ati intodus un numar!");
        } catch (RemoteException ex) {
            logger.error(ex);
            JOptionPane.showMessageDialog(null, "Eroare");
        }catch(Exception ex){
            logger.error(ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
